<a href="https://colab.research.google.com/github/Yash-Agarwal-4a5h/Machine-Learning/blob/main/ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
40   39    Male     Good    School        No
19   97    Male     Poor        PG       Yes
45   61    Male     Poor        PG       Yes
29   83  Female  Average        UG       Yes
6    18    Male     Good    School        No

In [10]:
df = df.iloc[:,2:]

In [11]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],
                                                    df.iloc[:,-1],
                                                    test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((40, 2), (40,), (10, 2), (10,))

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
X_train

review education
32  Average        UG
12     Poor    School
5   Average    School
30  Average        UG
13  Average    School
6      Good    School
48     Good        UG
11     Good        UG
29  Average        UG
19     Poor        PG
41     Good        PG
14     Poor        PG
31     Poor    School
2      Good        PG
9      Good        UG
4   Average        UG
46     Poor        PG
25     Good    School
8   Average        UG
43     Poor        PG
21  Average        PG
28     Poor    School
40     Good    School
42     Good        PG
49     Good        UG
23     Good    School
10     Good        UG
18     Good    School
17     Poor        UG
39     Poor        PG
24  Average        PG
16     Poor        UG
27     Poor        PG
7      Poor    School
34  Average    School
35     Poor    School
45     Poor        PG
38     Good    School
15     Poor        UG
0   Average    School

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [19]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [20]:
X_train=oe.transform(X_train)

In [21]:
X_train

array([[1., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [1., 0.]])

In [22]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

## Label Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le=LabelEncoder()

In [26]:
le.fit(y_train)

LabelEncoder()

In [27]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [28]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [29]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [30]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 1])